### PR TITLE
Setting rsyslog to gather Shiblogs

### PR DESCRIPTION
**Pull request by davidoae**

### CODE REVIEW

**Comment by mrvisser** [comment]
It seems really odd that there isn't already an `imfiles` entry for the production web access logs -- they are in performance and staging. Are you able to confirm if web logs are being dished out to syslog as well in production?

That said, if there should be, then we'd typically use local0 for web info and local1 for web error. Not sure if that would change your decision to use local1 for both shib info and warn logs.

**Comment by mrvisser** [comment]
Assigned back to @davidoae for feedback.

**Comment by simong** [comment]
The nginx logs [get configured in nginx.conf itself](https://github.com/oaeproject/puppet-hilary/blob/master/modules/nginx/templates/nginx.conf.erb#L15)

**Comment by mrvisser** [comment]
@simong ah right, thanks.

@davidoae should the shib_warn logs be sent with severity "warn" instead of "info"? Once that's resolved I think this is good to go.

**Comment by davidoae** [comment]
@mrvisser I see no disadvantage having the severity level at info, I see no advantage to changing it to warning. If there's a reason then I'll change it.
I note that travis checks are failing, there's some bad binary garbage in the log.

**Pull request merged**
