### PR TITLE
Nginx should use UDP to log to syslog

### PR DESCRIPTION
**Pull request by simong**
Fixes logging in production

### CODE REVIEW

**Comment by simong** [comment]
I'm going to be sneaky and merge in my own PR as I need this to investigate the etherpad issue.

**Comment by mrvisser** [comment]
@simong sneaker! Why is this needed to get etherpad logs?

**Comment by simong** [comment]
Etherpad's export PDF function was giving 504's. I was hoping that this would pop up in the nginx logs and allow me to find the original offending document.

**Comment by mrvisser** [comment]
@simong I'm speaking specifically to switching to UDP logs, why does UDP result in you now being able to look at Nginx logs?

**Comment by simong** [comment]
I'm not sure, but I think it has never been able to log using TCP. The last log from web0 on rsyslog was from 10 oct, which is when the previous change was made.

**Pull request merged**
